from setuptools import find_packages, setup

setup(
    name='notifications-python-client-govbr',
    version='0.0.1',
    packages=find_packages(),
    install_requires=['requests>=2.0.0',
        'PyJWT>=1.5.1',
        'docopt>=0.3.0',
        'monotonic>=0.1',
        'future',],
    include_package_data=True,
    license='MIT',
    description='Python API client for GOV.BR Notifica.',
    long_description='Python API client for GOV.UK Notify.',
    url='https://github.com/inacioloy/notifications-python-client',
    author='Inacio Loyola',
    author_email='inacioloy@gmail.com',
    classifiers=[
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Development Status :: 4 - Beta',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    ],
)
